// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {erlang} from '../models';

export function CalculateMetrics(arg1:erlang.MetricsRequest):Promise<erlang.MetricsResponse>;
